### PR TITLE
Add info to README to check if CI jobs run

### PR DESCRIPTION
**Pull request by ovirt-infra**

### CODE REVIEW

**Comment by ovirt-infra** [comment]
ci check please

**Comment by ovirt-infra** [comment]
ci check please

**Comment by ovirt-infra** [comment]
ci check please

**Comment by ovirt-infra** [comment]
ci check please

**Comment by ifireball** [comment]
ci test please

**Comment by ifireball** [comment]
ci build pelase

**Comment by ifireball** [comment]
ci build please

**Comment by ifireball** [comment]
ci 👍

**Comment by ifireball** [comment]
ci build please

**Comment by ifireball** [comment]
ci test please

**Comment by ifireball** [comment]
ci test please

**Comment by ifireball** [comment]
ci test please

**Comment by ifireball** [comment]
ci test please

**Comment by ifireball** [comment]
ci test please

**Comment by ifireball** [comment]
ci test please

**Comment by ifireball** [comment]
ci test please

**Comment by ovirt-infra** [comment]
There was an error with the build:

You are not in the whitelist, please ask to be added.

**Comment by ifireball** [comment]
ci test please

**Comment by ovirt-infra** [comment]
--none--

**Comment by ifireball** [comment]
ci test please

**Comment by ifireball** [comment]
ci test please

**Comment by ifireball** [comment]
ci test please

**Comment by ifireball** [comment]
ci test please

**Comment by ifireball** [comment]
ci test please

**Comment by ifireball** [comment]
ci test please

**Comment by ifireball** [comment]
ci test please

**Comment by ifireball** [comment]
ci test please

**Comment by ifireball** [comment]
ci build please

**Comment by ifireball** [comment]
ci test please

**Comment by ifireball** [comment]
ci test please

**Comment by ifireball** [comment]
ci test please

**Comment by ifireball** [comment]
ci test please

**Comment by ifireball** [comment]
ci test please

**Comment by ifireball** [comment]
ci test please

**Comment by ifireball** [comment]
ci test please

**Comment by ifireball** [comment]
ci test please

**Comment by ifireball** [comment]
ci test please

**Comment by ifireball** [comment]
ci test please

**Comment by ifireball** [comment]
ci test please

**Comment by ifireball** [comment]
ci test please

**Comment by ifireball** [comment]
ci test please

**Comment by ifireball** [comment]
ci test please

**Comment by ifireball** [comment]
ci test please

**Comment by ifireball** [comment]
ci test please

**Comment by ifireball** [comment]
ci test please

**Comment by ifireball** [comment]
ci test please

**Comment by ifireball** [comment]
ci test please

**Comment by ifireball** [comment]
ci test please

**Comment by ifireball** [comment]
ci test please

**Comment by ovirt-infra** [comment]
Can one of the admins verify this patch?

**Comment by ovirt-infra** [comment]
Can one of the admins verify this patch?

**Comment by ifireball** [comment]
@sandrobonazzola can you please close this? td would've been nice if you didn't try to assign this dusty stuff to me in the first place, the chances of any of this to remain relevant are zero, and I can't seem to be able to close this on my own.

**Comment by sandrobonazzola** [comment]
Closing as requested

**Pull request closed without merging**
