### PR TITLE
Create otpr.txt

### PR DESCRIPTION
**Pull request by ovirttest**

### CODE REVIEW

**Comment by ovirt-infra** [comment]
Can one of the admins verify this patch?

**Comment by ovirt-infra** [comment]
Can one of the admins verify this patch?

**Comment by ovirt-infra** [comment]
Can one of the admins verify this patch?

**Comment by ovirt-infra** [comment]
Can one of the admins verify this patch?

**Comment by ovirttest** [comment]
ci test please

**Comment by ovirt-infra** [comment]
Can one of the admins verify this patch?

**Comment by ovirt-infra** [comment]
Can one of the admins verify this patch?

**Comment by ovirt-infra** [comment]
Can one of the admins verify this patch?

**Comment by ovirt-infra** [comment]
Can one of the admins verify this patch?

**Comment by sandrobonazzola** [comment]
Closing stale PRs. Please reopen if still relevant.

**Pull request closed without merging**
