### PR TITLE
Add automation.yaml file for testing

### PR DESCRIPTION
**Pull request by danielBelenky**

### CODE REVIEW

**Comment by danielBelenky** [comment]
ci test please

**Comment by danielBelenky** [comment]
ci test please

**Comment by danielBelenky** [comment]
ci test please

**Comment by danielBelenky** [comment]
ci test please

**Comment by danielBelenky** [comment]
ci test please

**Comment by danielBelenky** [comment]
ci test please

**Comment by danielBelenky** [comment]
ci test please

**Comment by danielBelenky** [comment]
ci test please

**Comment by danielBelenky** [comment]
ci test please

**Comment by danielBelenky** [comment]
ci test please

**Comment by ovirt-infra** [comment]
Can one of the admins verify this patch?

**Comment by ovirt-infra** [comment]
Can one of the admins verify this patch?

**Comment by sandrobonazzola** [comment]
Closing stale PRs. Please reopen if still relevant.

**Pull request closed without merging**
